### ISSUE TITLE
Use `document.querySelectorAll` and class names for buttons

### ISSUE THREAD

**Issue by MadLittleMods** [Costava/Parity-Ship#7]
Using tag names to differentiate and target menu items is really sketchy.

[_source `main.js`_](https://github.com/Costava/Parity-Ship/blob/52817a43463a64633a484c8448a9211505c96f66/src/scripts/main.js#L151)

```
var buttons = menu.getElementsByTagName('button');
```

Consider using `document.querySelectorAll` and a relevant class name like `.menu-button`.

I also recommend using something like [`bling.js`](https://gist.github.com/paulirish/12fb951a8b893a454b32) which is a small micro dom manipulation library. I also made [my own flavor of `bling.js`](https://gist.github.com/MadLittleMods/8dd8443de3923f4a1d0c) that adds a few more bells and whistles.

---

Instead of using id's to individually target a certain button, use a class name like `.js-play-button` to signify that selector is for a JavaScript hook and not CSS styling. This also means your UI is extensible to add other "play" buttons anywhere else on the page.

[_offending code source_](https://github.com/Costava/Parity-Ship/blob/52817a43463a64633a484c8448a9211505c96f66/src/scripts/main.js#L830-L847)

**Comment by Costava** [comment]
Fixed with 56e13438dd495a8ea46fbef6b5a1bbc82e6300fd.
