### ISSUE TITLE
ES6 template strings could clean up all the string Concats

### ISSUE THREAD

**Issue by MadLittleMods** [Costava/Parity-Ship#8]
[ES6 template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings). You can use these ES6 features today and still support older browsers with a transpiler like [Babel](https://babeljs.io/). I also suggest pairing that up with something like [`webpack`](https://webpack.github.io/).

```
let greeting = `Hello ${name}`;
```

---

[_source_](https://github.com/Costava/Parity-Ship/blob/52817a43463a64633a484c8448a9211505c96f66/src/scripts/main.js#L61)

``` js
return 'rgb('+this.r+','+this.g+','+this.b+')';
// Could become:
return `rgb(${this.r}, ${this.g}, ${this.b})`;
```

**Comment by Costava** [comment]
Fixed with ca242295a0a5609ab3fd7a0f90c12b7fe266f0e1
