### ISSUE TITLE
Split out code into separate modules

### ISSUE THREAD

**Issue by MadLittleMods** [Costava/Parity-Ship#9]
Use a module system (ES6 modules, RequireJS, CommonJS) and a bundler.

For example `Color`, `Game`, `Ship`, `CleanPacket` can each be in their own separate file.

Then your `main.js` can look like a small bootstrap script

``` js
import Game from './lib/game`;

let game = new Game();

// ...element bindings
```

---

I suggest native ES6 modules with [Babel](https://babeljs.io/) and [webpack](https://webpack.github.io/).

Related to #8

**Comment by MadLittleMods** [comment]
Some instructions for setting up Babel and webpack:
- `npm init`
- `npm install babel webpack --save-dev`
- Save `webpack.config.js` in the root of the project

`webpack.config.js`

``` js
var path = require('path');

module.exports = {
    entry: './src/scripts/main.js',
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    devtool: 'source-map',
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel'
            }
        ]
    }
};
```
- In `package.json`, add to the `scripts` section:

```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build-dev": "webpack --watch --progress",
    "build": "webpack -p"
},
```
- Now just run `npm run build-dev` when developing which will watch for any changes and rebuild the bundle.
- `npm run build` when you are ready to make a production ready build.
- Don't forget to update the script reference in [`src/index.html`](https://github.com/Costava/Parity-Ship/blob/52817a43463a64633a484c8448a9211505c96f66/src/index.html#L79) to use `bundle.js` instead of `main.js`

**Comment by Costava** [comment]
Code split into modules with 9f1accfb1e2564788592a32285cd84b823ca006f and 57bcd9a51e3fbca216fffc92e2630541b4ad2fab.
